listofpokemon = """Here is the list of Pokemon:
    1. Bulbasaur
    2. Ivysaur
    3. Venasaur
    4. Charmander
    5. Charmeleon
    6. Charizard
    7. Squirtle
    8. Wartortle
    9. Blastoise
    10. Pidgey
    11. Pidgeotto
    12. Pidgeot
    13. Magikarp
    14. Gyarados
    15. Pikachu
    16. Raichu
    17. Cubone
    18. Marowak
    19. Weedle
    20. Kakuna
    21. Beedrill
    22. Rhyhorn
    23. Rhydon
    24. Lapras
    25. Eevee
    26. Vaporeon
    27. Flareon
    28. Jolteon
    29. Abra
    30. Kadabra
    31. Alakazam
    32. Gastly
    33. Haunter
    34. Gengar
    35. Dratini
    36. Dragonair
    37. Dragonite
    38. Jigglypuff
    39. Wigglytuff
    """

