moveinfo = {'Magnet Bomb':(30, 'Steel', 5, 20),
            'Hurricane':(80, 'Flying', 1, 10),
            'Air Cutter':(30, 'Flying', 3, 9),
            'Rock Tomb':(30, 'Rock', 4, 12),
            'Rock Slide':(50, 'Rock', 2, 7),
            'Rock Throw':(12, 'Rock', 35, 8),
            'Thunder Punch':(40, 'Electric', 3, 7),
            'Psychic':(55, 'Psychic', 2, 5),
            'Ancient Power':(35, 'Rock', 3, 6),
            'Fire Fang':(10, 'Fire', 30, 4),
            'Flame Wheel':(40, 'Fire', 3, 8),
            'Play Rough':(55, 'Normal', 2, 6),
            'Disarming Voice':(25, 'Normal', 6, 15),
            'Feint Attack':(12, 'Dark', 20, 6),
            'Pound':(7, 'Normal', 30, 1),
            'Psycho Cut':(7, 'Psychic', 35, 3),
            'Confusion':(15, 'Psychic', 20, 8),
            'Dazzling Gleam':(55, 'Normal', 2, 9),
            'Psybeam':(40, 'Psychic', 2, 3),
            'Signal Beam':(45, 'Bug', 3, 8),
            'Psyshock':(40, 'Psychic', 3, 6),
            'Zen Headbutt':(12, 'Psychic', 20, 7),
            'Bullet Punch':(10, 'Steel', 20, 6),
            'Submission':(30, 'Fighting', 4, 9),
            'Low Sweep':(30, 'Fighting', 5, 15),
            'Cross Chop':(60, 'Fighting', 2, 15),
            'Low Kick':(5, 'Fighting', 35, 1),
            'Karate Chop':(6, 'Fighting', 35, 1),
            'Hyper Beam':(100, 'Normal', 1, 15),
            'Dragon Breath':(6, 'Dragon', 30, 3),
            'Wrap':(25, 'Normal', 5, 12),
            'Shadow Ball':(40, 'Ghost', 3, 10),
            'Shadow Claw':(11, 'Ghost', 20, 10),
            'Ominous Wind':(30, 'Ghost', 5, 8),
            'Dark Pulse':(40, 'Dark', 3, 10),
            'Sucker Punch':(7, 'Dark', 35, 5),
            'Lick':(5, 'Ghost', 35, 1),
            'Bone Club':(25, 'Ground', 3, 3),
            'Rock Smash':(15, 'Fighting', 15, 5),
            'Discharge':(35, 'Electric', 4, 20),
            'Thunderbolt':(50, 'Electric', 2, 10),
            'Heat Wave':(70, 'Fire', 1, 6),
            'Swift':(20, 'Normal', 3, 3),
            'Dig':(70, 'Ground', 1, 6),
            'Body Slam':(30, 'Normal', 3, 10),
            'Fire Blast':(100, 'Fire', 1, 10),
            'Dragon Claw':(30, 'Dragon', 3, 5),
            'Wing Attack':(7, 'Flying', 30, 3),
            'Fire Punch':(40, 'Fire', 3, 15),
            'Ember':(10, 'Fire', 25, 4),
            'Flame Charge':(20, 'Fire', 3, 4),
            'Flamethrower':(55, 'Fire', 2, 8),
            'Flame Burst':(30, 'Fire', 2, 4),
            'Scratch':(8, 'Normal', 35, 2),
            'Tackle':(12, 'Normal', 35, 5),
            'Power Whip':(60, 'Grass', 1, 7),
	    'Solar Beam':(100, 'Grass', 1, 15),
	    'Razor Leaf':(15, 'Grass', 20, 7),
            'Seed Bomb':(40, 'Grass', 3, 6),
            'Vine Whip':(7, 'Grass', 30, 4),
            'Flash Cannon':(60, 'Steel', 1, 3),
            'Water Gun':(7, 'Water', 30, 4),
            'Water Pulse':(25, 'Water', 4, 6),
            'Aqua Tail':(45, 'Water', 2, 4),
            'Aqua Jet':(45, 'Water', 4, 6),
            'Bubble':(10, 'Water', 25, 8),
            'Megahorn':(70, 'Bug', 1, 5),
            'Stone Edge':(70, 'Rock', 2, 20),
            'Earthquake':(80, 'Ground', 1, 20),
            'Horn Attack':(20, 'Normal', 4, 6),
            'Bulldoze':(30, 'Ground', 3, 15),
            'Rock Smash':(10, 'Rock', 20, 8),
            'Mud Slap':(10, 'Ground', 20, 8),
            'Ice Beam':(30, 'Ice', 3, 10),
            'Blizzard':(80, 'Ice', 1, 11),
            'Frost Breath':(7, 'Ice', 30, 4),
            'Ice Shard':(15, 'Ice', 15, 8),
            'Spark':(7, 'Electric', 15, 5),
            'Thunder':(80, 'Electric', 1, 10),
            'Brick Break':(30, 'Fighting', 2, 10),
            'Quick Attack':(7, 'Normal', 35, 0),
            'Thunder Shock': (10,'Electric',10, 6),
            'Splash':(0, 'Water',35,1),
            'Struggle': (10, 'Normal',2, 10),
            'Fly': (12,'Flying',8, 8),
            'Gust': (30, 'Flying',2, 8),
            'Twister':(20, 'Dragon',4, 7),
            'Poison Sting':(5,'Poison',35, 2),
            'Bug Bite':(5, 'Bug',35, 3),
            'Sludge Bomb':(60, 'Poison',2, 9),
            'Bite':(8, 'Dark', 20, 4),
            'Dragon Pulse':(65, 'Dragon', 2, 7),
            'Hydro Pump':(90, 'Water', 1, 10),
            'Steel Wing':(13, 'Steel', 15, 7),
            'Poison Jab':(10, 'Poison', 15, 3),
            'X-Scissor':(35, 'Bug', 2, 6),
            'Aerial Ace':(25, 'Flying', 3, 4),
            '?a5':(50, '???', 30, -1),
            '?b22':(60, '???', 25, 5),
            '???':(300, '???', 1, -1),
            '??':(200, '???', 2, -1),
            '?':(100, '???', 6, -1)}
