weakness = {'Normal':('Fighting', '???'),
            'Flying':('Ice', 'Electric', 'Rock', '???'),
            'Water':('Electric', 'Grass', '???'),
            'Fire':('Water', 'Rock', 'Ground', '???'),
            'Grass':('Fire', 'Poison', 'Bug', 'Ice', 'Flying', '???'),
            'Bug':('Fire', 'Flying', 'Rock', '???'),
            'Ice':('Fire', 'Steel', 'Fighting', 'Rock', '???'),
            'Rock':('Water', 'Grass', 'Ground', 'Fighting', 'Steel', '???'),
            'Ground':('Water', 'Grass', 'Ice', '???'),
            'Electric':('Ground', '???'),
            'Psychic':('Bug', 'Ghost', 'Dark', '???'),
            'Fighting':('Psychic', 'Flying', '???'),
            'Poison':('Psychic', 'Ground', '???'),
            'Steel':('Ground', '???', 'Fire', 'Fighting'),
            'Ice':('Rock', 'Steel', '???'),
            'Ghost':('Ghost', 'Dark', '???'),
            'Dragon':('Dragon', 'Ice', '???'),
            'Dark':('Fighting', 'Bug'),
            '???':('lol')}
